openapi: 3.0.0
info:
  title: blog-api
  contact: {}
  version: "1.0"
servers:
  - url: https://blog-server-wto6.onrender.com/api/v1
    variables: {}
paths:
  /auth/register:
    post:
      tags:
        - Authentication
      summary: register user
      operationId: registeruser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/registeruserrequest"
                - {}
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
  /auth/login:
    post:
      tags:
        - Authentication
      summary: login user
      operationId: loginuser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/loginuserrequest"
                - example:
                    email: john@email.com
                    password: password
            example:
              email: john@email.com
              password: password
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
  /posts:
    post:
      tags:
        - Posts
      summary: create post
      operationId: createpost
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/createpostrequest"
                - {}
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
    get:
      tags:
        - Posts
      summary: get posts
      operationId: getposts
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
  /posts/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The post ID
    get:
      tags:
        - Posts
      summary: get post
      operationId: getpost
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
    patch:
      tags:
        - Posts
      summary: update post
      operationId: updatepost
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/updatepostrequest"
                - example:
                    published: true
            example:
              published: true
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
    delete:
      tags:
        - Posts
      summary: delete post
      operationId: deletepost
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
  /posts/upload:
    post:
      tags:
        - Posts
      summary: upload photo
      operationId: uploadphoto
      parameters: []
      requestBody:
        content:
          multipart/form-data:
            encoding: {}
            schema:
              required:
                - image
              type: object
              properties:
                image:
                  type: string
                  format: binary
        required: false
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
  /drafts:
    get:
      tags:
        - Drafts
      summary: get drafts
      operationId: getdrafts
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
  /drafts/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The draft ID
    get:
      tags:
        - Drafts
      summary: get draft
      operationId: getdraft
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
  /posts/{id}/comments:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The post ID
    get:
      tags:
        - Comments
      summary: get comments
      operationId: getcomments
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
    post:
      tags:
        - Comments
      summary: create comment
      operationId: createcomment
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/createcommentsrequest"
                - example:
                    content: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                    name: john
            example:
              content: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
              name: john
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
  /posts/{postId}/comments/{commentId}:
    parameters:
      - in: path
        name: postId
        schema:
          type: string
        required: true
        description: The post ID
      - in: path
        name: commentId
        schema:
          type: string
        required: true
        description: The comment ID
    delete:
      tags:
        - Comments
      summary: delete comment
      operationId: deletecomment
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}

  /posts/activity:
    get:
      tags:
        - Users
      summary: get activity
      operationId: getactivity
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
  /users:
    get:
      tags:
        - Users
      summary: get users
      operationId: getusers
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
  /users/{id}:
    parameters:
      - in: path
        name: id
        schema:
          type: string
        required: true
        description: The user ID
    get:
      tags:
        - Users
      summary: get user
      operationId: getuser
      parameters: []
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
  /users/profile/edit:
    patch:
      tags:
        - Users
      summary: edit user
      operationId: edituser
      parameters: []
      requestBody:
        description: ""
        content:
          application/json:
            schema:
              allOf:
                - $ref: "#/components/schemas/edituserrequest"
                - example:
                    name: john
            example:
              name: john
        required: true
      responses:
        "200":
          description: ""
          headers: {}
      deprecated: false
      security:
        - bearer: []
      servers:
        - url: https://blog-server-wto6.onrender.com/api/v1
          variables: {}
components:
  schemas:
    registeruserrequest:
      title: registeruserrequest
      required:
        - name
        - email
        - password
        - bio
        - image
      type: object
      properties:
        name:
          type: string
        email:
          type: string
        password:
          type: string
        bio:
          type: string
        image:
          type: string
    createpostrequest:
      title: createpostrequest
      required:
        - title
        - content
        - image
      type: object
      properties:
        title:
          type: string
        content:
          type: string
        image:
          type: string
    loginuserrequest:
      title: loginuserrequest
      required:
        - email
        - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
      example:
        email: john@email.com
        password: password
    createcommentsrequest:
      title: createcommentsrequest
      required:
        - content
        - name
      type: object
      properties:
        content:
          type: string
        name:
          type: string
      example:
        content: Lorem ipsum dolor sit amet, consectetur adipiscing elit.
        name: john
    updatepostrequest:
      title: updatepostrequest
      required:
        - published
      type: object
      properties:
        published:
          type: boolean
      example:
        published: true
    edituserrequest:
      title: edituserrequest
      required:
        - name
      type: object
      properties:
        name:
          type: string
      example:
        name: john
  securitySchemes:
    bearer:
      type: http
      scheme: bearer
security: []
tags:
  - name: Authentication
    description: ""
  - name: Posts
    description: ""
  - name: Drafts
    description: ""
  - name: Comments
    description: ""
  - name: Users
    description: ""
